version: '3.1'

services:
  php:
    image: php:7.2-apache
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080

  phpmyadmin:
    depends_on:
      - db
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - '8081:8081'
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: root

